=== sdmcclain/resume-demo/data/resumes/schemas/resume.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Resume Schema",
  "type": "object",
  "properties": {
    "personalInformation": {
      "type": "object",
      "properties": {
        "title": { "type": "string" },
        "summary": { "type": "string" }
      }
    },
    "highlights": {
      "type": "array",
      "items": { "type": "string" }
    },
    "accomplishments": {
      "type": "array",
      "items": { "type": "string" }
    },
    "professionalExperience": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "position": { "type": "string" },
          "company": { "type": "string" },
          "location": { "type": "string" },
          "startDate": { "type": "string" },
          "endDate": { "type": "string" },
          "responsibilities": {
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": ["position", "company", "startDate"]
      }
    },
    "education": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "degree": { "type": "string" },
          "field": { "type": "string" },
          "institution": { "type": "string" },
          "location": { "type": "string" },
          "graduationDate": { "type": "string" },
          "startDate": { "type": "string" },
          "endDate": { "type": "string" },
          "gpa": { "type": "string" }
        },
        "required": ["degree", "institution"]
      }
    },
    "skills": {
      "type": "array",
      "items": { "type": "string" }
    },
    "certifications": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "date": { "type": "string" }
        },
        "required": ["name"]
      }
    },
    "militaryService": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "branch": { "type": "string" },
          "rank": { "type": "string" },
          "startDate": { "type": "string" },
          "endDate": { "type": "string" },
          "responsibilities": {
            "type": "array",
            "items": { "type": "string" }
          }
        }
      }
    },
    "interests": {
      "type": "array",
      "items": { "type": "string" }
    }
  },
  "required": ["personalInformation", "professionalExperience"]
}

=== sdmcclain/resume-demo/data/resumes/processed/10219099.json
{
  "personalInformation": {
    "summary": "SkilledÂ Maintenance MechanicÂ Technician with superb problem solving and multi-tasking skills. Self-directed and motivated worker. To obtain a position where Teamwork, Integrity and Proffesionalism are a high standard in the Company's Mission Statement. All while engaing in new challenges and learning experiences.",
    "title": "EQUIPMENT ENGINEERING TECHNICIAN"
  },
  "professionalExperience": [
    {
      "company": "Company Name",
      "position": "Equipment Engineering Technician",
      "startDate": "05/2014",
      "endDate": "Current",
      "location": "City, State",
      "responsibilities": [
        "Responsibility for designing/selecting robotic systems, run simulation, implementation, commission and programming.",
        "Support and assist maintenance team in troubleshooting difficult breakdowns and chronic equipment failures.",
        "Conduct the installation of factory automation and electrical control systems for manufacturing equipment Provide Troubleshooting of electrical systems in plant manufacturing equipment Provide effective direction, coaching, and OJT to fellow employees on shift to boost their skill sets, and help Production achieve their goals.",
        "Plan and organize between shift and weekend work, including verification, for smooth operations.",
        "Assist the Supervisor in developing PMs and procedures for maintaining all of the equipment in the shop.",
        "Provide shift-to-shift communication in order to keep all associates up to speed and working toward the same goals.",
        "Set an example, and ensure that all associates comply with safety regulations and the plant's safety program",
        "Work with engineers and fellow technicians to resolve technical problems.",
        "Assist in candidate selection as requested.",
        "Maintain departmental records Maintain spare parts inventory.",
        "Identify and order needed parts, maintain tracking system.",
        "Perform other duties as assigned by the Supervisor and Manager."
      ]
    },
    {
      "company": "Company Name",
      "position": "Mechanical Technician",
      "startDate": "04/2013",
      "endDate": "05/2014",
      "location": "City, State",
      "responsibilities": [
        "Implement repair services on all production equipment, auxiliary equipment and building equipment using hand tools, testing tools, manual drawings, computer and any other tools necessary to accomplish the task.",
        "Provide reliable, high quality customer support through on-site inspecting, installing, repairing and/or replacing fire alarm equipment as well as conducting preventive maintenance services pertaining to many different manufacturers equipment.",
        "Ensure conveyor belts working effectively"
      ]
    },
    {
      "company": "Company Name",
      "position": "Operating Engineer / Test Technician",
      "startDate": "11/2007",
      "endDate": "06/2012",
      "location": "City, State",
      "responsibilities": [
        "Operates, repair and maintain Facility/Plant Machinery, Test Equipment, Lubrication and Cooling Systems and High Pressure Systems for NASA unitary Wind Tunnels.",
        "Constructs, modifies, maintains and services wind and propulsion tunnel research facilities used to test models of aircraft components, utilizing knowledge of engineering test methods and procedures.",
        "Installs and aligns mechanical hydraulic and pneumatic test equipment and models on support structures.",
        "Installs instrumentation, thermocouples and pressure taps on model and test equipment.",
        "Inspects test setup and operates equipment to detect and correct malfunctions.",
        "Maintains instrumentation equipment and accessories for pressure valves, icing indicators, drive units, spray units, and pumps.",
        "Confers with engineering and other personnel during testing and modifies model, test support structure, or test equipment as directed.",
        "Inspect, test, and install fire sprinkler systems, standpipe systems, fire pumps, and clean agent systems at various industrial, commercial and institutional facilities in accordance with various codes.",
        "Perform inspections, test and repair/replace fire hoses and fire hydrants.",
        "Generate reports based on inspection findings."
      ]
    },
    {
      "company": "Company Name",
      "position": "Logistics Coordinator / Sr. Lab technician",
      "startDate": "10/2006",
      "endDate": "11/2007",
      "location": "City, State",
      "responsibilities": [
        "Coordinates all incoming and outgoing shipments of solar arrays, panels, shipping containers and ground support equipment."
      ]
    },
    {
      "company": "Company Name",
      "position": "Production Control Analyst",
      "startDate": "11/2004",
      "endDate": "05/2006",
      "location": "City, State",
      "responsibilities": [
        "Expedites materials through production processes, coordinates actions with other departments, verifies kit hardware completeness and configuration, requests drawings and materials to be issued from stores.",
        "Resolves aging work orders, generates Non-conforming Material Reports (NCMR's).",
        "Interfaces with process engineers, manufacturing operators and supervisors to control and analyze the movement of production.",
        "Resolves complex constraints for any WIP that may cause schedule delays, problem solve all audit issue on work centers.",
        "Perform internal and external expediting of critical parts and initiate and process scrap tags, and process miscellaneous issue requests.",
        "Extensive use of the Promis software.",
        "Trains new hires in Class 100 clean room protocol and enforces violations.",
        "Procurement of all clean room articles and consumables with outside vendors.",
        "Supervises courier team of 5 to ensure proper transport of company assets from site to site."
      ]
    },
    {
      "company": "Company Name",
      "position": "Material/Production Planner",
      "startDate": "07/2001",
      "endDate": "02/2004",
      "location": "City, State",
      "responsibilities": [
        "Expedites materials through production processes, coordinates actions with other departments, verifies kit hardware completeness and configuration, requests drawings and materials to be issued from stores.",
        "Resolves aging work orders, generates Non-conforming Material Reports (NCMR's), and generates shipping packing lists and invoice documents.",
        "Responsible for scheduling, releasing, updating, and closing work orders in a timely manner.",
        "Reports oral and written status of work progress to internal customers.",
        "Interfaces with all Operations functions"
      ]
    }
  ],
  "education": [
    {
      "degree": "General Courses",
      "institution": "Monterey Peninsula College",
      "location": "City, State"
    },
    {
      "degree": "Technical Diploma",
      "institution": "San Francisco Police Academy",
      "location": "City, State"
    }
  ],
  "skills": [
    "automation",
    "closing",
    "coaching",
    "oral",
    "hardware",
    "customer support",
    "designing",
    "direction",
    "hand tools",
    "inventory",
    "ISO 9001",
    "Machinery",
    "materials",
    "mechanical",
    "personnel",
    "processes",
    "Procurement",
    "programming",
    "progress",
    "quality",
    "Quality Control",
    "Receiving",
    "repairs",
    "repairing",
    "research",
    "robotic systems",
    "safety",
    "scheduling",
    "shipping",
    "simulation",
    "Supervisor",
    "Test Equipment",
    "Troubleshooting",
    "written",
    "articles"
  ]
}

=== sdmcclain/resume-demo/data/resumes/processed/70750649.json
{
  "personalInformation": {
    "title": "DIRECTOR OF PR & SOCIAL MEDIA\nExecutive Profile"
  },
  "professionalExperience": [
    {
      "company": "Company Name",
      "position": "Director of PR & Social Media",
      "startDate": "06/2015",
      "endDate": "Current",
      "location": "City, State",
      "responsibilities": [
        "Lead the PR & Social Media Strategy for the relaunch of dELiA*s, successfully repositioning the company as a leading teen brand among its competitors.",
        "Managed critical sponsorship opportunities for dELiA*s with Teen Vogue's Back To School Program, 5 Seconds of Summer Concert Series, BearPaw x dELiA*s free ads on the Geoffrey Tron Screen in Times Square.",
        "Secured extensive Press & Social Media coverage for dELiA*s November Catalog Cover: Teen wonderchef and NY Times Cover Star, Flynn McGarry.",
        "Spearheaded and managed the PR & Social Media Campaigns for Alloy Apparel that took critical market share and social media footprint from Long Tall Sally as a leader in Tall Women's Clothing in 6 months.",
        "Initiated the use of User Generated Content (UGC)on each brand's website and paid ads, resulting in a substantial increase in positive brand sentiment, brand awareness and brand revenue",
        "Increased brand revenue for both companies through social media efforts that amounted revenue 5 times bigger than the initial investment.",
        "Created a brand ambassador program for both companies that included a series of high-profile bloggers, influencers and celebrities at no cost for each brand that served as a continuous form of income and brand awareness",
        "Collaborated with E-Commerce and Marketing to support and drive key promotions organically as well as through paid media campaigns",
        "Provided in-depth data analysis and social media reporting for each brand",
        "Managed budgets and made best use of budgetary funds",
        "Managed an internal team of 3, an external PR agency, an external ad agency, 1 UGC management agency.",
        "Nurtured & cultivated strong relationships with Fashion Directors, key Trade, Ad and Finance publications, Fashion Stylists and Bloggers in the contemporary and teen markets."
      ]
    },
    {
      "company": "Company Name",
      "position": "PR Manager",
      "startDate": "02/2012",
      "endDate": "06/2015",
      "location": "City, State",
      "responsibilities": [
        "Primary Press Liaison for Foley+Corinna, Isabella Fiore, Snob Essentials, Charlotte Ronson, L.A.M.B.and NARR.",
        "Managed a staff of 4 employees for the development and execution of global public relations, event planning, marketing and advertising programs in the US and South Korea.",
        "Secured a continuous stream of high-profile celebrity, blogger, fashion influencer, TV, print and web placements for each brand.",
        "Secured strategic partnerships with the CFDA, Faberge's Big Egg Hunt, Christie's, Studio in A School, Covet Fashion, Refinery29 Shops, Celebrity Exotics, Lucky Shops, SpringNYC at no cost for the company.",
        "Seasonally collaborated with Seventh House PR, Factory PR, HL Group, Autumn Communications, Paul Wilmot Communications during event & fashion show production, West Coast initiatives and celebrity seeding opportunities.",
        "Initiated and lead the Brand Revival initiative for Isabella Fiore."
      ]
    },
    {
      "company": "Company Name",
      "position": "Account Executive",
      "startDate": "07/2011",
      "endDate": "02/2012",
      "location": "City, State",
      "responsibilities": [
        "Managed 8 client accounts (Jewelry, Accessories, Contemporary Clothing, Handbags, Denim)",
        "Secured numerous high-visibility product placements by maintaining close communications with major celebrity representatives/stylists, top editors, bloggers and high-fashion tastemakers.",
        "Brought in 21 new potential client accounts within a 2-month period",
        "Spearheaded and organizing partnerships/collaborations with charity organizations (Project: Camille Zarsky - Charity Water)",
        "Introduced a dynamic collaboration initiative and celebrity endorsements for up-and-coming designers",
        "Supervised social media activity for 3 client accounts",
        "Spearheaded Shine Media's international service outreach in Paris",
        "Produced a tangible increase in brand awareness and customer demand for each client."
      ]
    },
    {
      "company": "Company Name",
      "position": "PR & Marketing Coordinator",
      "startDate": "09/2009",
      "endDate": "02/2010",
      "location": "City, State",
      "responsibilities": [
        "Handled all communications with press, media, stylists and celebrities.",
        "Researched and secured 12 luxury advertising partners.",
        "Covered shows and conducted interviews with designers during New York Fashion Week (September 2009).",
        "Negotiated new high-profile partnership opportunities."
      ]
    },
    {
      "company": "Company Name",
      "position": "Public Relations Executive",
      "startDate": "01/2009",
      "endDate": "07/2011",
      "location": "City, State",
      "responsibilities": [
        "Managed all client accounts (Ready-to-Wear, Accessories, Lifestyle, Hospitality, Education.",
        "Secured the most magazine covers and celebrity placements in the history of the agency (Beyonce, Rihanna, Taylor Swift, Vanessa Hudgens, Kelly Clarkson, Scarlett Johansson, Paris Hilton, etc.)",
        "Wrote, formatted and disseminated key press materials (press and news releases, fact sheets, bios, newsletters).",
        "In charge of the agency's social media pages, website content updates and email newsletter.",
        "Actively seeked & secured new partnership and sponsorship opportunities (Swarovski, CFDA).",
        "Produced annual reports, new client proposals, new marketing and advertising material for the agency and its clients.",
        "Communicated daily with major national & international publications, newspapers, stylists and bloggers regarding sample requests and media placements.",
        "Fostered relationships and networking opportunities with colleagues, clients and media.",
        "Organized and produced Fashion Week presentations, launch events and press previews for a variety of clients.",
        "Managed the US press for the Inaugural Event of the Burj Khalifa Tower in Dubai."
      ]
    },
    {
      "company": "Company Name",
      "position": "Public Relations Associate",
      "startDate": "08/2008",
      "endDate": "10/2008",
      "location": "City, State",
      "responsibilities": [
        "Assisted in all aspects of preparation and production of eight fashion shows during New York Fashion Week (Mara Hoffman, Alexandre Herchcovitch, Buckler, Sabyasatchi, Yigal Azrouel, Araks, Jeremy Scott, House of Holland)",
        "Preparation and execution of high-profile events and after-parties during Fashion Week",
        "Created daily and monthly Press Clips",
        "Updated Press, Trade and Media Contact Lists,",
        "Responsible sample trafficking and sample database."
      ]
    },
    {
      "company": "Company Name",
      "position": "Public Relations & Global Communications Assistant",
      "startDate": "11/2007",
      "endDate": "05/2008",
      "location": "City, State",
      "responsibilities": [
        "Played a key role in the communications for the launch of Vera Wang's new advertising campaign in Greece.",
        "Assisted in the production of Vera Wang's Ready-to-Wear and Lavender Label fashion shows during NY fashion week (February 2008).",
        "Responsible for sample trafficking to publications (sending, monitoring and receiving samples).",
        "Created monthly credit reports."
      ]
    },
    {
      "company": "Company Name",
      "position": "Marketing Intern",
      "startDate": "11/2007",
      "endDate": "04/2007",
      "location": "City, State",
      "responsibilities": [
        "Assisted during company presentations to new clients.",
        "Edited press and marketing materials.",
        "Communicated with high-end accounts and delivered brand assets as needed (Barneys, Selfridges, Harvey Nichols, The Mandarin Oriental).",
        "Handled all sample requests."
      ]
    }
  ],
  "education": [
    {
      "degree": "Master of Science : Marketing",
      "institution": "UNIVERSITY OF BATH",
      "endDate": "9/2006",
      "location": "City, United Kingdom"
    },
    {
      "degree": "Bachelor of Science : International Economic & Political Studies",
      "institution": "UNIVERSITY OF MACEDONIA",
      "endDate": "9/2005",
      "location": "City, Greece",
      "startDate": "9/2005"
    }
  ],
  "skills": [
    "MAC OS",
    "Microsoft Office",
    "Word",
    "Excel",
    "PowerPoint",
    "Outlook",
    "Photoshop",
    "Cision",
    "Fashion GPS",
    "Social Annex"
  ]
}

=== sdmcclain/resume-demo/data/resumes/processed/37058472.json
{
  "personalInformation": {
    "summary": "Designer with more than 15 years in product design, manufacturing, exhibit design and visual merchandising, with comprehensive management and logistics experience who thrives in dynamically changing environments.",
    "title": "DESIGNER"
  },
  "professionalExperience": [
    {
      "company": "Designer Company Name",
      "position": "Designer",
      "startDate": "03/2014",
      "endDate": "11/2015",
      "location": "City, State",
      "responsibilities": [
        "Design and built custom furniture from client's initial conceptual idea.",
        "Create CAD drawings for approval",
        "Create estimate of pricing",
        "Provide finish samples and fabrics cuttings for approval, Creates, reviews, and modifies all specification documentation including approval drawings, supplier drawings, and all specifications.",
        "Responsible for correct building and finishing of product designed",
        "Completed key projects on time, on budget and with a high level of accuracy.",
        "Reviewed production orders, schedules, delivery dates and inventory levels to determine product availability.",
        "Established and adjusted work procedures to meet production schedules.",
        "Supervised production schedules, production quality and on time delivery."
      ]
    },
    {
      "company": "Senior Production Manager Company Name",
      "position": "Senior Production Manager",
      "startDate": "02/2006",
      "endDate": "03/2014",
      "location": "City, State",
      "responsibilities": [
        "Management of Production team",
        "Responsible for price quotations of all custom quotes in the Formations product line.",
        "Also responsible for accurate generation of Order Acknowledgment and related approval drawings when necessary, and review and launch of \"Standard\" product line.",
        "Worked closely with R&D department, assisting as necessary in the development of new products.",
        "Created, reviewed, and modified all specification documentation including approval drawings, supplier drawings, and all specifications in the MAS 200 system, and E2 ShopTec System",
        "Reviewed and maintained pricing for all Formations product line, meeting directly with owners to evaluate value-engineering concepts and options.",
        "Developed, evaluated, and maintained the quality of our vendors and products.",
        "Prepared analysis of new designs for overall feasibility and possible incorporation into the standard line of products.",
        "Responsible to oversee and supervise the team in production of all products verifying proper assembly techniques, finishes, upholstery, and development of necessary implementation.",
        "Communicated and instructed sales to assure a smooth flow of information throughout the production process.",
        "Maintained average turn-around on all custom quotes and estimates.",
        "Assisted in the daily questions and issues related to \"Custom\" work and/or engineering of orders to the respective department supervisors, when necessary.",
        "Authorized the fulfillment of requests for repairs, orders returns/cancellation and discounts.",
        "Interacted with all managers to solve/discuss issues, concerns, updates, projects, and deadlines for all demands."
      ]
    },
    {
      "company": "Project Manager Company Name",
      "position": "Project Manager",
      "startDate": "06/2004",
      "endDate": "11/2005",
      "location": "City, State",
      "responsibilities": [
        "Space and furniture planning",
        "Design capabilities along with strong organizational and communication skills, creation of FF&E, color & materials.",
        "Coordination of drawings and information with other disciplines while providing design support for completion and execution of design projects (space planning, details, specifications, material palettes).",
        "Served as the single point of contact for project scheduling and changes.",
        "Monitored team progress and enforced deadlines.",
        "Drafted action plans and led meetings with department executives to review project status and proposed changes.",
        "Defined project deliverables and monitored status of tasks.",
        "Responsible for small maintenance projects as the Viceroy Hotel in Santa Monica."
      ]
    }
  ],
  "accomplishments": [
    "Planned, directed, coordinated and assigned manpower to efficiently meet production requirements."
  ],
  "education": [
    {
      "degree": "Associate of Arts : Interior and Furniture Design",
      "institution": "Santa Monica College",
      "location": "City, State"
    },
    {
      "degree": "Bachelor of Laws (LLB)",
      "institution": "Contract Universidade Candido Mendes",
      "location": "City, State, Brazil"
    }
  ],
  "highlights": [
    "Design processing expertise",
    "Proficient in AutoCAD",
    "Adobe Photoshop",
    "Concept development",
    "Product specifications",
    "Color and material application",
    "Strong leader",
    "Proficient with furniture systems",
    "Vendor sourcing",
    "Knowledgeable of quality control standards",
    "Procurement specialist",
    "Dedication to product quality",
    "Compliance with GMPs"
  ],
  "skills": [
    "AutoCad drafting",
    "3D Rendering",
    "Material Board",
    "Communication skills",
    "conceptual design",
    "material organizational",
    "Fluent in Portuguese and English",
    "Intermediate Spanish"
  ]
}
